# Digital Methods 2020
# twitter app credentials

CONSUMER_KEY = 'YOUR CONSUMER KEY HERE'
CONSUMER_SECRET = 'YOUR CONSUMER SECRET HERE'
ACCESS_TOKEN = 'YOUR ACCESS TOKEN HERE'
ACCESS_TOKEN_SECRET = 'YOUR ACCESS TOKEN SECRET HERE'
